application: ted-me-up
version: 1
runtime: python
api_version: 1
threadsafe: no

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?test$
- ^(.*/)?test$
- ^Makefile
- ^COPYING.LESSER
- ^README.md
- \.gitignore
- ^\.git/.*
- \.*\.lint$

builtins:
- appstats: on #/_ah/stats/
- remote_api: on #/_ah/remote_api/

handlers:
- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: \1
  upload: (robots\.txt|humans\.txt|crossdomain\.xml)

- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  mime_type: text/css
  static_dir: css

- url: /res
  mime_type: application/json
  static_dir: res

- url: /js
  mime_type: text/javascript
  static_dir: js

- url: /img/(.*\.(gif|png|jpg))
  static_files: img/\1
  upload: img/(.*\.(gif|png|jpg))

- url: /.*
  script: main.py